name: Get GitHub Info
on: [workflow_dispatch]
jobs:
  github-info:
    runs-on: ubuntu-latest
    steps:
    - name: Print Github Info
      run: echo "${{ toJson(github) }}"
    - name: Print Runtime Repo URL
      run: echo "URL:- ${{ github.repositoryUrl }}"