name: nodejs_workflows
on: push
jobs:
  node_jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
      name: install Node ENV
    - name: Install NPM Packages
      run: npm ci
    - name: Test NPM
      run: npm test
    # - name: Run Command
    #   run: |
    #     ls -la
    #     pwd