name: nodejs_workflows
on: push
jobs:
  node_jobs:
    runs_on: ubuntu_latest
    steps:
    - name: Get Code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
      name: install node
    - name: Run Command
      run: |
        ls -la
        pwd